### ISSUE TITLE
【功能增加或修改】建议任务详情页内增加 "立即运行" 和 "查看日志" 选项功能；建议修改APP 图标为青龙原版logo。

### ISSUE THREAD

**Issue by Memorainer** [relax976/qinglong_app#1]
![Snipaste_2023-02-09_13-30-48](https://user-images.githubusercontent.com/17745131/217726708-224261f3-c5fd-4acd-9bf6-c476f94fe1f0.png)

1.如图
2.两个大字logo总感觉有点不太聪明的样子，b格不够

**Comment by relax976** [comment]
右上角按钮里有运行
