### ISSUE TITLE
[BUG]地址填域名会提示出错

### ISSUE THREAD

**Issue by maxqq001** [relax976/qinglong_app#4]
当前 Web 端服务是否可用
：可用

**Bug 描述**
步骤，是否必现，最好有图片或者视频
![qinglong](https://user-images.githubusercontent.com/116856376/220832452-1c06e704-d984-42c5-9eec-1d804933176a.jpg)
地址填域名会出错
域名为花生壳域名

**版本信息**
App 版本， Android还是 iOS，青龙面板的版本，手机型号和操作系统的版本
  3.0                 Android                  2.10.13

**Comment by RUInalan** [comment]
我也是，好像是证书的问题
